# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-29 05:06
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='accountId',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
