# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-29 17:41
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0004_auto_20171029_1720'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('dataPoints', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
        migrations.AlterField(
            model_name='chart',
            name='sensor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='public.Asset'),
        ),
        migrations.DeleteModel(
            name='Sensor',
        ),
    ]
